export const ACTION_ADD_TODO = 'ADD_TODO';
export const ACTION_TOGGLE_TODO = 'TOGGLE_TODO';
export const ACTION_SET_VISIBILITY_FILTER = 'SET_VISIBILITY_FILTER';

export const STATE_SHOW_ALL = 'SHOW_ALL';
export const STATE_SHOW_COMPLETED = 'SHOW_COMPLETED';
export const STATE_SHOW_ACTIVE = 'SHOW_ACTIVE';
